config/routes.rb
Rails.application.routes.draw do

  resources :items, :occasions, :pages, :lineitem, :cart, :orders, :charges

  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create]
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_item(item_id, quantity)
    current_item = lineitems.find_by_item_id(item_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = lineitems.build(:item_id => item_id, :quantity => quantity)
    end
    current_item
  end

def total_price
  lineitems.to_a.sum do |item|
    item.total_price
  end
end

def total_items
  lineitems.to_a.sum do |item|
    item.quantity
  end
end

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_and_belongs_to_many :occasions
    has_many :lineitems
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  # belongs_to :items
  belongs_to :order
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price  * quantity
  end

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  has_and_belongs_to_many :items
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_line_items_from_cart(cart)
    cart.lineitems.each do |lineitem|
      lineitem.cart_id = nil
      lineitems << lineitem
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :orders
  has_one :cart
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

end

app/controllers/cart_controller.rb
class CartController < ApplicationController


  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def create
  end

  def new
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new

  end

  def index
    @item = Item.all
  end

  def create
      item = Item.create item_params
      redirect_to items_path
    end

    def update
      item = Item.find params[:id]
      item.update item_params
      redirect_to items_path
    end

    def edit
      @item = Item.find params[:id]
    end

    def show
      @item = Item.find params[:id]
      @gifts = Item.where(:kind => 'Gift')
    end

    def destroy
      item = Item.find params[:id]
      item.destroy
      redirect_to items_path
    end

    private
    def item_params
      params.require(:item).permit(:name, :description, :image, :price, :kind)
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new

    @cart = current_cart
    if @cart.lineitems.empty?
      redirect_to root_path, :notice => "Your cart is empty"
      return
    end

    @order = Order.new
  end


  def create

    begin
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => (current_cart.total_price * 100).to_i,
        :description => 'Rails Stripe customer',
        :currency    => 'aud'
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
    end

    # create an order from cart lineitems
    @order = Order.new
    @order.add_line_items_from_cart(current_cart)
    @order.user_id = @current_user.id
    @order.totalprice = current_cart.total_price

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      redirect_to root_path, flash: {notice: "Thank you for your order!"}
    else
      redirect_to root_path, flash: {notice: "Error saving order!"}
    end

  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    begin
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      # need to set cart.user_id = session[:user_id]
      session[:cart_id] = cart.id
      cart
    end
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitem_helper.rb
module LineitemHelper
end

app/helpers/occasion_helper.rb
module OccasionHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/create.html.erb
<h2>Pay Now</h2>

app/views/orders/destroy.html.erb
<h1>Order#destroy</h1>
<p>Find me in app/views/order/destroy.html.erb</p>

app/views/orders/index.html.erb
<h1>Order#index</h1>
<p>Find me in app/views/order/index.html.erb</p>

app/views/orders/new.html.erb
<h2>Your Order</h2>

<div class="container orderDisplayContainer ">

<% @cart.lineitems.each do |lineitem| %>
  <div class="row">
    <div class="col-md-3">
        <div class="title"> <%= lineitem.item.name %></div>
    </div>
    <div class="col-md-3">
        <img src="<%= lineitem.item.image %>" class="thumbAdmin"/>
   </div>
   <div class="col-md-3">
        <div class=""><%= lineitem.quantity %> x <%= lineitem.item.price %></div>
   </div>
   <div class="col-md-3">
     <div class=""><%= lineitem.total_price %></div>
   </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6"></div>
  <div class="col-md-3">
      <div class="title">Grand Total:</div>
  </div>
  <div class="col-md-3">
      <div class="title"> <%= @cart.total_price %></div>
  </div>
</div>

  <!-- <%= link_to 'Pay Now', new_charge_path ,class: 'btn btn-info'%> -->

  <%= form_tag orders_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Order Payment"
        data-amount="<%= @cart.total_price * 100 %>"
        data-locale="auto"></script>
<% end %>
</div>

app/views/orders/update.html.erb
<h1>Order#update</h1>
<p>Find me in app/views/order/update.html.erb</p>