config/routes.rb
Rails.application.routes.draw do

  resources :items, :occasions, :pages, :lineitem, :cart, :orders, :charges

  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create]
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_item(item_id, quantity)
    current_item = lineitems.find_by_item_id(item_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = lineitems.build(:item_id => item_id, :quantity => quantity)
    end
    current_item
  end

def total_price
  lineitems.to_a.sum do |item|
    item.total_price
  end
end

def total_items
  lineitems.to_a.sum do |item|
    item.quantity
  end
end

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_and_belongs_to_many :occasions
    has_many :lineitems
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  # belongs_to :items
  belongs_to :order
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price  * quantity
  end

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  has_and_belongs_to_many :items
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_line_items_from_cart(cart)
    cart.lineitems.each do |lineitem|
      lineitem.cart_id = nil
      lineitems << lineitem
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :orders
  has_one :cart
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

end

app/controllers/cart_controller.rb
class CartController < ApplicationController


  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def create
  end

  def new
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new

  end

  def index
    @item = Item.all
  end

  def create
      item = Item.create item_params
      redirect_to items_path
    end

    def update
      item = Item.find params[:id]
      item.update item_params
      redirect_to items_path
    end

    def edit
      @item = Item.find params[:id]
    end

    def show
      @item = Item.find params[:id]
      @gifts = Item.where(:kind => 'Gift')
    end

    def destroy
      item = Item.find params[:id]
      item.destroy
      redirect_to items_path
    end

    private
    def item_params
      params.require(:item).permit(:name, :description, :image, :price, :kind)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
   @occasion = Occasion.find(7)
    # redirect_to occasions_path
    # raise "Hell"
  end
  def show
    @occasion = Occasion.find params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:author, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    begin
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      # need to set cart.user_id = session[:user_id]
      session[:cart_id] = cart.id
      cart
    end
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitem_helper.rb
module LineitemHelper
end

app/helpers/occasion_helper.rb
module OccasionHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class="col-md-4 col-md-offset-2">
    <%= form_for @item, :html => {:class => "form-horizontal center"} do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.url_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.radio_button(:kind, "Flowers") %>
        <%= f.label(:kind_Flowers, "Flowers") %>
        <%= f.radio_button(:kind, "Gift") %>
        <%= f.label(:kind_Gift, "Gift") %>
    </div>
    <div class="form-group">
        <%= f.submit  "Save Item" , class: 'btn btn-default'%>
    </div>
    <% end %>
</div>
<!-- t.text     "name"
t.text     "description"
t.text     "image"
t.money    "price",       scale: 2
t.datetime "created_at",            null: false
t.datetime "updated_at",            null: false
t.text     "kind" -->

app/views/items/edit.html.erb
<h1> Edit Item</h1>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<h1>All Items</h1>
<ul>
    <li><%= link_to 'New Item', new_item_path %></li>
</ul>
<div class="container">
    <div class="row">
        <!-- <div class="col-md-4"> -->
            <div class="col-md-offset-0">
                <table class="table table-bordered table-striped">
                    <tr>
                        <td>Name</td>
                        <td>Description</td>
                        <td>Image</td>
                        <td>Price</td>
                        <td>Type</td>
                        <td>Actions</td>
                    </tr>
                    <% @item.each do |itm| %>
                    <% if (itm.kind =='Flowers') %>
                    <tr>
                        <td><%= itm.name %></td>
                        <td><%= itm.description %></td>
                        <td><%= image_tag itm.image, :class => 'thumbAdmin' %></td>
                        <td><%= itm.price %></td>
                        <td><%= itm.kind %> </td>
                        <td>
                            <%= link_to 'Show', itm %>
                            <%= link_to 'Edit', edit_item_path(itm) %>
                            <%= link_to 'Destroy', itm, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                    <% end %>
                    <% end %>

                </table>
            </div>
        <!-- </div> -->
        <!-- close left column -->
        <div class="col-md-4">
            <div class="col-md-4 col-md-offset-0">
                <table class="table table-bordered table-striped">
                    <tr>
                        <td>Name</td>
                        <td>Description</td>
                        <td>Image</td>
                        <td>Price</td>
                        <td>Type</td>
                        <td>Actions</td>
                    </tr>

                    <% @item.each do |itm| %>
                    <% if (itm.kind =='Gift') %>
                    <tr>
                        <td><%= itm.name %></td>
                        <td><%= itm.description %></td>
                        <td><%= image_tag itm.image, :class => 'thumbAdmin' %></td>
                        <td><%= itm.price %></td>
                        <td><%= itm.kind %></td>
                        <td><%= link_to 'Show', itm %>
                            <%= link_to 'Edit', edit_item_path(itm) %>
                            <%= link_to 'Destroy', itm, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                    <% end %>
                    <% end %>
                </table>
            </div>
        </div>
        <!-- close row -->
    </div>
    <!-- close right column -->
</div>
<!-- close container -->

app/views/items/new.html.erb
<h2>Create New Item</h2>
<div class="col-md-4 col-md-offset-2">
  <%= form_for @item, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.url_field :image %>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<div class="form-group">
    <%= f.radio_button(:kind, "Flowers") %>
    <%= f.label(:kind_Flowers, "Flowers") %>

    <%= f.radio_button(:kind, "Gift") %>
    <%= f.label(:kind_Gift, "Gift") %>
</div>
<div class="form-group">
  <%= f.submit  "Save Item" %>
</div>
<% end %>
</div>
<!-- t.text     "name"
t.text     "description"
t.text     "image"
t.money    "price",       scale: 2
t.datetime "created_at",            null: false
t.datetime "updated_at",            null: false
t.text     "kind" -->

app/views/items/show.html.erb
<!-- <h1>Show Items</h1> -->
<div class="col-md-4 col-md-offset-2">
    <%= image_tag @item.image, :class => 'thumb' %><br><br>
        <span class="label label-info occLabelClass">
            <%= @item.name %>
            $<%= @item.price %>
            <%= link_to "Add Gift", "javascript:;",{  :class => "addGiftLink", :'data-target' => '#addGift', :'data-toggle' => "modal"}%>
            <button id="btnCart" type="button" class="btn btn-info addToCart" item_id="<%= @item.id %>">Add To Cart</button>
            <%= link_to 'Checkout', new_order_path %>

        </span>


    <% if @current_user.present? && @current_user.admin? %>
        <%= @item.kind %> |
        <%= link_to 'Edit', edit_item_path(@item) %> |
        <%= link_to 'Delete', @item, :method => :delete %>
    <% end %>
</div>
 <!-- This div is for shoppingCart, this id is called in custom.js -->
    <div id="shoppingCartView">
    </div>



<!-- //Code for model popup for Gifts -->
<div id="addGift" class="modal fade addGiftPanel" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Gift</h4>
            </div>
            <div class="modal-body">

                <div class="container">
                  <div class="row rowModalPopup">

                    <% @gifts.each do |gift| %>
                    <div class="col-md-4 colModalPopup">
                            <%= image_tag gift.image, :class => 'thumbAdmin' %><br>
                            <%= gift.name %><br>
                            <%= gift.price %><br>
                            <button type="button" class="btn btn-info addToCart" item_id="<%= gift.id %>">Add To Cart</button>
                        </div>

                    <% end %>
                </div>
            </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>