config/routes.rb
Rails.application.routes.draw do

  resources :items, :occasions, :pages, :lineitem, :cart, :orders, :charges

  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create]
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_item(item_id, quantity)
    current_item = lineitems.find_by_item_id(item_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = lineitems.build(:item_id => item_id, :quantity => quantity)
    end
    current_item
  end

def total_price
  lineitems.to_a.sum do |item|
    item.total_price
  end
end

def total_items
  lineitems.to_a.sum do |item|
    item.quantity
  end
end

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_and_belongs_to_many :occasions
    has_many :lineitems
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  # belongs_to :items
  belongs_to :order
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price  * quantity
  end

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  has_and_belongs_to_many :items
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_line_items_from_cart(cart)
    cart.lineitems.each do |lineitem|
      lineitem.cart_id = nil
      lineitems << lineitem
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :orders
  has_one :cart
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

end

app/controllers/cart_controller.rb
class CartController < ApplicationController


  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def create
  end

  def new
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new

  end

  def index
    @item = Item.all
  end

  def create
      item = Item.create item_params
      redirect_to items_path
    end

    def update
      item = Item.find params[:id]
      item.update item_params
      redirect_to items_path
    end

    def edit
      @item = Item.find params[:id]
    end

    def show
      @item = Item.find params[:id]
      @gifts = Item.where(:kind => 'Gift')
    end

    def destroy
      item = Item.find params[:id]
      item.destroy
      redirect_to items_path
    end

    private
    def item_params
      params.require(:item).permit(:name, :description, :image, :price, :kind)
    end
  end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController

  

  def new
    @occasion = Occasion.new
  end

  def index
    @occasion = Occasion.all

  end



  def create
      occasion = Occasion.create occasion_params
      redirect_to occasions_path
    end

    def update
      occasion = Occasion.find params[:id]
      occasion.update occasion_params
      redirect_to occasion
    end

    def edit
      @occasion = Occasion.find params[:id]
    end

    def show
      @occasion = Occasion.find params[:id]
    end

    def destroy
      occasion = Occasion.find params[:id]
      occasion.destroy
      redirect_to occasions_path
    end

    private
    def occasion_params
      params.require(:occasion).permit(:name)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
   @occasion = Occasion.find(7)
    # redirect_to occasions_path
    # raise "Hell"
  end
  def show
    @occasion = Occasion.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    begin
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      # need to set cart.user_id = session[:user_id]
      session[:cart_id] = cart.id
      cart
    end
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitem_helper.rb
module LineitemHelper
end

app/helpers/occasion_helper.rb
module OccasionHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/occasions/_form.html.erb
<div class="col-md-4 col-md-offset-2">
  <%= form_for @occasion, :html => {:class => "form-horizontal center"} do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit  "Save Occasion" , class: 'btn btn-default'%>
  </div>
  <% end %>
</div>

app/views/occasions/edit.html.erb
<h1>Edit Occasions</h1>
<%= render :partial => 'form' %>

app/views/occasions/index.html.erb
<h1>
    All Occasions</h1>
    <div class="col-md-4 col-md-offset-2">
        <%= link_to 'New Occasion', new_occasion_path %>
<br>
<br>
    <% @occasion.each do |occ| %>
    <div class="form-group">
        <%= occ.name %> |
            <%= link_to 'Show', occ %>
            <%= link_to 'Edit', edit_occasion_path(occ) %>
            <%= link_to 'Delete', occ, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
</div>

app/views/occasions/new.html.erb
<h1>Create New Occasions</h1>
<%= render :partial => 'form' %>

app/views/occasions/show.html.erb
<!-- <h1><%= @occasion.name %></h1> -->

<div class="container">
  <div class="row">
  <% @occasion.items.each do |item| %>
  <% if (item.kind =='Flowers') %>
    <div class="col-md-3">
      <%= link_to image_tag(item.image, :class => 'thumb'), item %>
      <span class="label label-info fontSize">
          <div class="itemInfo">
              <%= item.name %>
              $<%= item.price %>
          </div>
      </span>
      <br>
      <br>
    </div>
    <% end %>
  <% end %>
  </div>
</div>


<!-- # <%= link_to 'Edit Occasion', edit_occasion_path(@occasion) %>
# <%= link_to 'Delete Occasion', @occasion, :method => :delete %> -->