config/routes.rb
Rails.application.routes.draw do

  resources :items, :occasions, :pages, :lineitem, :cart, :orders, :charges

  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create]
  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_item(item_id, quantity)
    current_item = lineitems.find_by_item_id(item_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = lineitems.build(:item_id => item_id, :quantity => quantity)
    end
    current_item
  end

def total_price
  lineitems.to_a.sum do |item|
    item.total_price
  end
end

def total_items
  lineitems.to_a.sum do |item|
    item.quantity
  end
end

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_and_belongs_to_many :occasions
    has_many :lineitems
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  # belongs_to :items
  belongs_to :order
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price  * quantity
  end

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  has_and_belongs_to_many :items
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :lineitems

  def add_line_items_from_cart(cart)
    cart.lineitems.each do |lineitem|
      lineitem.cart_id = nil
      lineitems << lineitem
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :orders
  has_one :cart
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    begin
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      # need to set cart.user_id = session[:user_id]
      session[:cart_id] = cart.id
      cart
    end
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitem_helper.rb
module LineitemHelper
end

app/helpers/occasion_helper.rb
module OccasionHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Florist</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <style>
    .topnav{
      margin-bottom: -1px !important;
    }
    .navbar.center .navbar-collapse {
        text-align: center;
    }

    .navbar.center .navbar-collapse .nav {
        display:inline-block;
        float: none;
    }
    </style>
    <body>
    <nav class="navbar navbar-default topnav">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Awesome Florist</a>
        </div>

      <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>
          <% if @current_user.present? %>
            <% if @current_user.admin? %>
             <li class="<%= 'active' if current_page?(occasions_path) %>"><%= link_to "Occasion", occasions_path %></li>
             <li class="<%= 'active' if current_page?(items_path) %>"><%= link_to "Item", items_path %></li>
            <% end %>
            <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to "Logout #{ @current_user.email }", login_path, :method => :delete %></li>
          <% else %>

            <li class="<%= 'active' if current_page?(signup_path) %>"><%= link_to "Sign up", signup_path %></li>
        <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to "Login", login_path %></li>
          <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                 <div id="idcartDisplay" class="cartDisplay">
                      Cart:<div id="cartCount"><%= current_cart.total_items %></div> Item<span id="cPlural"></span>
                      <div id="space"></div>
                      $<div id="cartPrice"><%= current_cart.total_price %></div>
                </div>
          </ul>
      </div>
            <!--/.nav-collapse -->
    </div>
        <!--/.container-fluid -->
    </nav>
<!-- second navbar for All Occasion categories -->
    <nav class="navbar navbar-default center">
      <div id="navbar-occasion" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% Occasion.all.each  do |occ| %>
          <li class="<%= 'active' if current_page?(occ) %>"><%= link_to occ.name, occasion_path(occ.id) %></li>
        <% end %>
      </ul>

    </nav>

    <% if flash[:error].present? %>
    <h2 class="error">
        <%= flash[:error] %>
    </h2>
    <% end %>

    <% if flash[:notice].present? %>
    <h2 class="notice">
        <%= flash[:notice] %>
    </h2>
    <% end %>

        <%= yield %>

    </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/welcome.html.erb
<!--  -->

<div class="container">
  <div class="row">
  <% @occasion.items.each do |item| %>
  <% if (item.kind =='Flowers') %>
    <div class="col-md-3">
      <%= link_to image_tag(item.image, :class => 'thumb'), item %>
      <span class="label label-info fontSize">
          <div class="itemInfo">
              <%= item.name %>
              $<%= item.price %>
          </div>
      </span>
      <br>
      <br>
    </div>
    <% end %>
  <% end %>
  </div>
</div>